### ISSUE TITLE
Unas cuantas preguntas

### ISSUE THREAD

**Issue by CageHN** [gaboesquivel/ama#1]
En que/con quien trabaja? Cuantos años de experiencia tiene? Como cree que este AMA le puede servir a los demas usuarios de "Web Costa Rica"? Que es DevOps?

**Comment by gaboesquivel** [comment]
Trabajo como freelancer y consultor independiente. En este momento estoy desarrollando un prototipo para aplicación que brinda servicios a viajeros frecuentes, es aplicación mobile híbrida con backend en Node. 

Tengo 6 años de experiencia, empecé en el 2009.  Ingresé a la Universidad en 2007 Cenfotec/Latina.

Espero a través de este repo poder compartir mi experiencia profesional y de vida con aquellas personas a quién pueda beneficiar. [Compartir el conocimiento adquirido es importante](http://costaricajs.co/2015/03/CostaRicaJS-Y-que-me-gano-yo).

DevOps es un movimiento de desarrolladores de software e ingenieros de operaciones que quieren derribar los muros y mejorar la relación entre entre desarrollo, operaciones y el resto de la empresa.
Es una respuesta a la interdependencia del desarrollo de software y las operaciones IT. Su objetivo es ayudar a una organización a producir productos y servicios de software rápidamente.
más en [devOps Costa Rica](http://devopscr.co/)
