### ISSUE TITLE
Why do you like programming?

### ISSUE THREAD

**Issue by a0viedo** [gaboesquivel/ama#2]

**Comment by gaboesquivel** [comment]
I enjoy the endless possibilities of the web platform, solving problems and engineering. 

I started when I was about 20 year old. I wanted to build a website my capoeira group ( I used to train that martial art ), I thought it was going to be simple, but then I realized it was complex. Initially I must admit I felt frustrated but then as learned more things I started to enjoy the development process and specially the results. The ability to reach people regardless their location, that's what I liked the most.

It also allowed me to work from anywhere I want.
