### ISSUE TITLE
Why did you join Gorilla Logic?

### ISSUE THREAD

**Issue by rubenabix** [gaboesquivel/ama#4]
Hey Gabo,
I would like to know why did you join Gorilla Logic?
How is it like to work there?

**Comment by gaboesquivel** [comment]
Hey Ruben! 

Gorilla is really awesome. So far it has been a great experience; I’ve learned so much, culture is excellent, everyone is kind and curious. They hire mostly senior developers, every lunch you can join really interesting conversations with people with different backgrounds. It feels good, there are no stupid rules and it’s a very flat, horizontal, open door company with outstanding leadership.

Every week there are jamming sessions, there are many good musicians here, impressive. The founders themselves join. Other people do yoga and every couple of weeks there’s a lunch and learn event where developers share their knowledge in many technologies.

Payment is adequate to your job ( unlike many other outsourcing companies in Costa Rica ).

It is a remote first company that gives you a lot freedom, what matters is that you do your job, there’s no one bossing around.

They are involved in the local development communities and meetups, hosting and sponsoring awesome events like nodeschool.

The office is really nice, it has an amazing view of San Jose and the National Stadium in Sabana.

I personally admire Mario Merino ( Managing Director in Costa Rica) very much, he’s very smart and supportive. Recently he introduced Mindfulness workshops, I participated in a 4 week workshop where we explored mindfulness techniques. I loved it. I continue practicing it and what I learned is elevating my quality of life and well-being; I have more energy, I’m productive and overall I’m happier. I would recommend to everyone reading this to give it a try. 

[What is Mindfulness?](https://www.youtube.com/watch?v=HmEo6RI4Wvs)

It’s definitely one of the best places to work in Costa Rica.
